import { ollamaService } from "../services/ollama.service";
import { navigate } from "../browser/actions";
import { scrapePage } from "../browser/scraper";
import { obsidianService } from "../services/obsidian.service";
import { logger } from "../services/logger.service";

export class ResearchAgent {
  async run(query: string, targetNotePath: string): Promise<string> {
    logger.info("ResearchAgent started", { query, targetNotePath });

    const searchUrl = `https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;

    try {
      await navigate(searchUrl);
      const { text: searchText, links } = await scrapePage();

      const contentLinks = links.filter(
        (l: string) =>
          l.startsWith("http") &&
          !l.includes("duckduckgo") &&
          !l.includes("duck.com")
      );

      if (contentLinks.length === 0) {
        return "ResearchAgent: no usable links found in search results.";
      }

      await navigate(contentLinks[0]);
      const { text: pageText } = await scrapePage();

      const summaryPrompt = `You are a research assistant. Summarize the following content in structured markdown.
Include: Key Points, Summary, and Source URL.
Source URL: ${contentLinks[0]}
Content: ${pageText.slice(0, 4000)}`;

      const summary = await ollamaService.generate(summaryPrompt);

      const noteContent = `# Research: ${query}
> Generated by ResearchAgent on ${new Date().toLocaleDateString()}

${summary}

---
**Source:** ${contentLinks[0]}
**Raw search results preview:**
${searchText.slice(0, 500)}
`;

      await obsidianService.writeNote(targetNotePath, noteContent);
      logger.info("ResearchAgent wrote note", { targetNotePath });

      return summary;
    } catch (err: any) {
      logger.error("ResearchAgent failed", { query, error: err.message });
      return `Error: research failed for query "${query}" — ${err.message}`;
    }
  }
}

export const researchAgent = new ResearchAgent();
